version: "3.9"  # optional since v1.27.0
services:
  postgres_cadastro:
    container_name: postgres_broker
    image: postgres:12.2
    environment:
      POSTGRES_USER: broker
      POSTGRES_PASSWORD: broker
    ports:
      - "5432:5432"
  jaeger_cadastro: 
    container_name: jaeger_cadastro
    image: jaegertracing/all-in-one:1.6
    ports: 
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
  prometheus:
    container_name: prometheus
    image: prometheus  
    network_mode: "host"
  grafana:
    container_name: grafana
    image: grafana/grafana:6.5.0  
    network_mode: "host"